
GET http://127.0.0.1:3000/items HTTP/1.1

###


POST http://127.0.0.1:3000/items HTTP/1.1
content-type:  application/json

{
    "id": 4,
    "name": "Item 4",
    "description": "This is the fourth item posted as json.",
    "price": 4.99
}

###

POST http://127.0.0.1:3000/items HTTP/1.1
content-type:  application/application/x-www-form-urlencoded

id=5&name=Item 5&description=Form posted this is the fifth item.&price=4.99


###


PUT http://127.0.0.1:3000/items/4 HTTP/1.1
content-type:  application/json

{
    "id": 4,
    "name": "Item 44",
    "description": "This is the fourth item put as json.",
    "price": 44.99
}


###

DELETE http://127.0.0.1:3000/items/5 HTTP/1.1
